### ISSUE TITLE
npm run build:all stuck in error

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#188]
Hello, 

In building schemas, the build script (`npm run build:all`) gets stuck when there has been an error. It's of course fine to get an error if something is wrong on a schema, but the script error remains after fixing the issue. 

Example: 
checkout -> npm run build:all -> All okay
add schemaXyz.json -> npm run build:all -> Error
remove schemaXyz.json -> npm run build:all -> Error persists

The only way I have found to get past this is deleting my entire local repo and re-checkout (which is quite frustrating).

Has anyone else experienced this? Is there an explanation and/or fix on how to deal with this? 

Thanks in advance! 

Nis
__________

Including the terminal output and the log. 

[2021-08-02T13_01_33_903Z-debug.log](https://github.com/w3c-ccg/traceability-vocab/files/6917096/2021-08-02T13_01_33_903Z-debug.log)

```
npm run build:all

> root@ build:all /Users/nis/Documents/git/traceability-vocab
> lerna run build:all --stream

lerna notice cli v3.22.1
lerna info Executing command in 1 package: "npm run build:all"
traceability-schemas: > traceability-schemas@1.0.0 prebuild:all /Users/nis/Documents/git/traceability-vocab/packages/traceability-schemas
traceability-schemas: > rm -rf ../../docs/schemas
traceability-schemas: > traceability-schemas@1.0.0 build:all /Users/nis/Documents/git/traceability-vocab/packages/traceability-schemas
traceability-schemas: > npm run build:schemas && npm run build:intermediate && npm run build:context && npm run build:test-vectors && npm run build:credentials && npm run build:validate && npm run build:vocab && npm run build:open-api && npm run lint
traceability-schemas: > traceability-schemas@1.0.0 build:schemas /Users/nis/Documents/git/traceability-vocab/packages/traceability-schemas
traceability-schemas: > node ./scripts/build-schemas.js && cp -r ./schemas ../../docs/schemas
traceability-schemas: 🧪 build an index.js from a directory of JSON files.
traceability-schemas: undefined:1
traceability-schemas: SyntaxError: Unexpected token  in JSON at position 0
traceability-schemas:     at JSON.parse (<anonymous>)
traceability-schemas:     at /Users/nis/Documents/git/traceability-vocab/packages/traceability-schemas/scripts/build-schemas.js:11:26
traceability-schemas:     at Array.forEach (<anonymous>)
traceability-schemas:     at buildFixturesFromFs (/Users/nis/Documents/git/traceability-vocab/packages/traceability-schemas/scripts/build-schemas.js:9:9)
traceability-schemas:     at Object.<anonymous> (/Users/nis/Documents/git/traceability-vocab/packages/traceability-schemas/scripts/build-schemas.js:22:13)
traceability-schemas:     at Module._compile (internal/modules/cjs/loader.js:1068:30)
traceability-schemas:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
traceability-schemas:     at Module.load (internal/modules/cjs/loader.js:933:32)
traceability-schemas:     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
traceability-schemas:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
traceability-schemas: npm ERR! code ELIFECYCLE
traceability-schemas: npm ERR! errno 1
traceability-schemas: npm ERR! traceability-schemas@1.0.0 build:schemas: `node ./scripts/build-schemas.js && cp -r ./schemas ../../docs/schemas`
traceability-schemas: npm ERR! Exit status 1
traceability-schemas: npm ERR! 
traceability-schemas: npm ERR! Failed at the traceability-schemas@1.0.0 build:schemas script.
traceability-schemas: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
traceability-schemas: npm ERR! A complete log of this run can be found in:
traceability-schemas: npm ERR!     /Users/nis/.npm/_logs/2021-08-02T13_01_33_797Z-debug.log
traceability-schemas: npm ERR! code ELIFECYCLE
traceability-schemas: npm ERR! errno 1
traceability-schemas: npm ERR! traceability-schemas@1.0.0 build:all: `npm run build:schemas && npm run build:intermediate && npm run build:context && npm run build:test-vectors && npm run build:credentials && npm run build:validate && npm run build:vocab && npm run build:open-api && npm run lint`
traceability-schemas: npm ERR! Exit status 1
traceability-schemas: npm ERR! 
traceability-schemas: npm ERR! Failed at the traceability-schemas@1.0.0 build:all script.
traceability-schemas: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
traceability-schemas: npm ERR! A complete log of this run can be found in:
traceability-schemas: npm ERR!     /Users/nis/.npm/_logs/2021-08-02T13_01_33_849Z-debug.log
lerna ERR! npm run build:all exited 1 in 'traceability-schemas'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@ build:all: `lerna run build:all --stream`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the root@ build:all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nis/.npm/_logs/2021-08-02T13_01_33_903Z-debug.log
```

**Comment by OR13** [comment]
try:

```
npx jest --clearCache
```

**Comment by OR13** [comment]
https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/traceability-schemas/scripts/build-schemas.js#L11

should be wrapped in try catch and re-throw with file name that caused problem.

**Comment by OR13** [comment]
```js
try {} catch(e){ console.error('filename: ', filename)}
```

**Comment by nissimsan** [comment]
https://github.com/w3c-ccg/traceability-vocab/pull/198

**Comment by nissimsan** [comment]
> try:
> 
> ```
> npx jest --clearCache
> ```
> 
> if this resolves this, we can add it as a `pre` step.

This has worked for me in the past; I recommend we include this too.

**Comment by nissimsan** [comment]
This is outdated now that the build process has changed - closing.
