### ISSUE TITLE
Address `npm run test` warnings

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#451]
We have a lot - A LOT! - of warnings generated when running test. I think step one here is to just go through it all and spawn issues on what needs to be done to address them. 

We want `npm run test` to complete without warnings.

Here's a sample (the actual list of warnings exceeded 65k chars.):

```
  ● Console

    console.error
      NaturalGasProductCertificate
       {
        "@context": [
          "https://www.w3.org/2018/credentials/v1",
          "https://w3id.org/traceability/v1"
        ],
        "type": [
          "VerifiableCredential",
          "NaturalGasProductCertificate"
        ],
        "id": "http://example.org/credentials/",
        "issuanceDate": "2021-02-04T20:29:37+00:00",
        "issuer": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
        "credentialSubject": {
          "type": "NaturalGasProduct",
          "HSCode": "270900",
          "UWI": "100.12-04-091-05-W5.00",
          "productionDate": "2020-03-30",
          "facility": {
            "type": "Place",
            "globalLocationNumber": "3278867908778",
            "geo": {
              "type": "GeoCoordinates",
              "latitude": "-45.1928",
              "longitude": "-120.8187"
            },
            "address": {
              "type": "PostalAddress",
              "organizationName": "Schneider - Bernier",
              "streetAddress": "012 Cecil Keys",
              "addressLocality": "Gaylordhaven",
              "addressRegion": "Indiana",
              "postalCode": "50459",
              "addressCountry": "Philippines"
            },
            "unLocode": "DKCPH"
          },
          "observation": [
            {
              "type": "Observation",
              "date": "2019-12-11T03:50:55Z",
              "property": {
                "type": "ChemicalProperty",
                "name": "Moscovium",
                "formula": "Mc"
              },
              "measurement": {
                "type": "MeasuredValue",
                "value": "00.00",
                "unitCode": "UNKNOWN"
              }
            }
          ],
          "product": {
            "type": "Product",
            "manufacturer": {
              "type": "Person",
              "firstName": "Chadd",
              "lastName": "Sipes",
              "email": "Frances23@example.net",
              "phoneNumber": "555-326-7995",
              "worksFor": {
                "type": "Organization",
                "name": "Rowe Inc",
                "description": "Multi-tiered bandwidth-monitored system engine",
                "address": {
                  "type": "PostalAddress",
                  "streetAddress": "2943 Cartwright Lock",
                  "addressLocality": "West Lanceburgh",
                  "addressRegion": "New Jersey",
                  "postalCode": "42420",
                  "addressCountry": "Russian Federation"
                },
                "email": "Melisa.Monahan19@example.org",
                "phoneNumber": "555-564-1276",
                "faxNumber": "555-554-6557"
              },
              "jobTitle": "Regional Tactics Producer"
            },
            "name": "Natural Gas",
            "description": "Natural Gas Stream",
            "sizeOrAmount": {
              "type": "QuantitativeValue",
              "unitCode": "hg/ha",
              "value": "4182"
            },
            "weight": {
              "type": "QuantitativeValue",
              "unitCode": "hg/ha",
              "value": "7369"
            },
            "sku": "523162922635"
          }
        },
        "proof": {
          "type": "Ed25519Signature2018",
          "created": "2022-06-20T15:28:51Z",
          "verificationMethod": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U#z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
          "proofPurpose": "assertionMethod",
          "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..JpIbqXQg6TS2jfRMnstZTwmNSM9IlR_CIPz1TfakE5UTtOLoW3n4ZuyeLJSjVbayMPWhWEg3amJXYOhzCCMqCw"
        }
      }
       [
        {
          keyword: 'const',
          dataPath: '/@context/0',
          schemaPath: '#/properties/%40context/items/const',
          params: { allowedValue: [Array] },
          message: 'should be equal to constant'
        }
      ]

      51 |         const isValid = ajv.validate(s.$id, input);
      52 |         if (!isValid) {
    > 53 |           console.error(s.$linkedData.term, '\n', s.example, '\n', ajv.errors);
         |                   ^
      54 |         }
      55 |
      56 |         return true;

      at __tests__/schemas-sanity.test.js:53:19
          at async Promise.all (index 136)
      at Object.<anonymous> (__tests__/schemas-sanity.test.js:37:18)

    console.error
      PGAStatusMessageCertificate
       {
        "@context": [
          "https://www.w3.org/2018/credentials/v1",
          "https://w3id.org/traceability/v1"
        ],
        "id": "https://example.com/credential/123",
        "type": [
          "VerifiableCredential",
          "PGAStatusMessageCertificate"
        ],
        "name": "PGA Status Message Certificate",
        "description": "Certificate Issued by a PGA for the status of Cargo",
        "relatedLink": [],
        "issuanceDate": "2019-12-11T03:50:55Z",
        "issuer": {
          "id": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
          "type": "Organization",
          "name": "Food Border Force Agency",
          "description": "Food Related PGA",
          "address": {
            "type": "PostalAddress",
            "streetAddress": "027 Brakus Knoll",
            "addressLocality": "East Johnniemouth",
            "addressRegion": "Arizona",
            "postalCode": "25780-5840",
            "addressCountry": "Grenada"
          },
          "email": "Kendrick.Spinka57@fbf.example.gov",
          "phoneNumber": "555-322-9464",
          "faxNumber": "555-766-1744"
        },
        "credentialSubject": {
          "items": [
            {
              "type": "PGAStatusMessage",
              "recordNo": "SO70",
              "entryNo": "AAA-1234567-8",
              "entryLineSequence": "L1:S1",
              "statusCode": "O2",
              "statusCodeDescription": "Hold Intact",
              "validCodeReason": "25",
              "validCodeReasonDescription": "Additional Verification Needed",
              "subReasonCode": "132",
              "subReasonCodeDescription": "Documentation Needed"
            },
            {
              "type": "PGAStatusMessage",
              "recordNo": "SO70",
              "entryNo": "AAA-1234567-8",
              "entryLineSequence": "L1:S2",
              "statusCode": "O7",
              "statusCodeDescription": "May Proceed",
              "validCodeReason": "23",
              "validCodeReasonDescription": "Released"
            }
          ]
        },
        "proof": {
          "type": "Ed25519Signature2018",
          "created": "2022-06-20T15:28:50Z",
          "verificationMethod": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U#z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
          "proofPurpose": "assertionMethod",
          "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19.._QwKB69jsdQc17d2JOqJqYAkrYjeLAcgj_SZeTQLucyTkZ0yVfwxpFnvpGacP4lRkzUPb2fRo9DWuH6-nVd4CQ"
        }
      }
       [
        {
          keyword: 'const',
          dataPath: '/@context/0',
          schemaPath: '#/properties/%40context/items/const',
          params: { allowedValue: [Array] },
          message: 'should be equal to constant'
        }
      ]

      51 |         const isValid = ajv.validate(s.$id, input);
      52 |         if (!isValid) {
    > 53 |           console.error(s.$linkedData.term, '\n', s.example, '\n', ajv.errors);
         |                   ^
      54 |         }
      55 |
      56 |         return true;

      at __tests__/schemas-sanity.test.js:53:19
          at async Promise.all (index 137)
      at Object.<anonymous> (__tests__/schemas-sanity.test.js:37:18)

    console.error
      PackingListCertificate
       {
        "@context": [
          "https://www.w3.org/2018/credentials/v1",
          "https://w3id.org/traceability/v1"
        ],
        "id": "did:key:z6MkiLRxCg43iGaSdpdadCcjWW1aoxZbsL9zvcnTV1TT5eYa",
        "type": [
          "VerifiableCredential",
          "PackingListCertificate"
        ],
        "issuanceDate": "2019-12-11T03:50:55Z",
        "issuer": {
          "type": "Entity",
          "id": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
          "name": "Xxinau Manufacturing Co. Ltd.",
          "description": "Advanced Production - Delivered",
          "address": {
            "type": "PostalAddress",
            "streetAddress": "Xin Fei Da Dao 139",
            "addressLocality": "Xindao",
            "addressRegion": "Fujian Province",
            "postalCode": "361100",
            "addressCountry": "CN"
          },
          "entityType": "Organization"
        },
        "credentialSubject": {
          "type": "PackingList",
          "orderNumber": "PO00000329",
          "seller": {
            "type": "Entity",
            "name": "Xxinau Manufacturing Co. Ltd.",
            "description": "Advanced Production - Delivered",
            "address": {
              "type": "PostalAddress",
              "streetAddress": "Xin Fei Da Dao 139",
              "addressLocality": "Xindao",
              "addressRegion": "Fujian Province",
              "postalCode": "361100",
              "addressCountry": "CN"
            },
            "entityType": "Organization"
          },
          "buyer": {
            "type": "Entity",
            "name": "By ACRE",
            "address": {
              "type": "PostalAddress",
              "streetAddress": "IC. Modewegs Vej 1",
              "addressLocality": "Kgs. Lyngby",
              "postalCode": "2800",
              "addressCountry": "DK"
            },
            "entityType": "Organization"
          },
          "shipFromParty": {
            "type": "Entity",
            "name": "Xxinau Manufacturing Co. Ltd.",
            "description": "Advanced Production - Delivered",
            "address": {
              "type": "PostalAddress",
              "streetAddress": "Xin Fei Da Dao 139",
              "addressLocality": "Xindao",
              "addressRegion": "Fujian Province",
              "postalCode": "361100",
              "addressCountry": "CN"
            },
            "entityType": "Organization"
          },
          "shipToParty": {
            "type": "Entity",
            "name": "By ACRE",
            "address": {
              "type": "PostalAddress",
              "streetAddress": "IC. Modewegs Vej 1",
              "addressLocality": "Kgs. Lyngby",
              "postalCode": "2800",
              "addressCountry": "DK"
            },
            "entityType": "Organization"
          },
          "handlingInstructions": [
            {
              "type": "Instructions",
              "description": "Handle with care"
            }
          ],
          "partOfOrder": [
            {
              "type": "PartOfOrder",
              "packageQuantity": 540,
              "transportPackages": [
                {
                  "type": "Package",
                  "physicalShippingMarks": "by ACRE AGE IS THE NEW BLACK",
                  "perPackageUnitQuantity": 1,
                  "includedTradeLineItems": [
                    {
                      "type": "TradeLineItem",
                      "description": "Rollators",
                      "itemCount": 540
                    }
                  ],
                  "netWeight": {
                    "type": "QuantitativeValue",
                    "value": "3834",
                    "unitCode": "kg"
                  },
                  "grossWeight": {
                    "type": "QuantitativeValue",
                    "value": "4302",
                    "unitCode": "kg"
                  },
                  "grossVolume": {
                    "type": "QuantitativeValue",
                    "value": "66.96",
                    "unitCode": "cbm"
                  }
                }
              ]
            },
            {
              "type": "PartOfOrder",
              "packageQuantity": 2,
              "transportPackages": [
                {
                  "type": "Package",
                  "physicalShippingMarks": "by ACRE AGE IS THE NEW BLACK",
                  "perPackageUnitQuantity": 100,
                  "includedTradeLineItems": [
                    {
                      "type": "TradeLineItem",
                      "description": "Rollator backrest",
                      "itemCount": 200
                    }
                  ],
                  "netWeight": {
                    "type": "QuantitativeValue",
                    "value": "42",
                    "unitCode": "kg"
                  },
                  "grossWeight": {
                    "type": "QuantitativeValue",
                    "value": "44",
                    "unitCode": "kg"
                  },
                  "grossVolume": {
                    "type": "QuantitativeValue",
                    "value": "0.28",
                    "unitCode": "cbm"
                  }
                }
              ]
            },
            {
              "type": "PartOfOrder",
              "packageQuantity": 80,
              "transportPackages": [
                {
                  "type": "Package",
                  "physicalShippingMarks": "by ACRE AGE IS THE NEW BLACK",
                  "perPackageUnitQuantity": 1,
                  "includedTradeLineItems": [
                    {
                      "type": "TradeLineItem",
                      "description": "Rollator backrest",
                      "itemCount": 80
                    }
                  ],
                  "netWeight": {
                    "type": "QuantitativeValue",
                    "value": "50",
                    "unitCode": "kg"
                  },
                  "grossWeight": {
                    "type": "QuantitativeValue",
                    "value": "160",
                    "unitCode": "kg"
                  },
                  "grossVolume": {
                    "type": "QuantitativeValue",
                    "value": "0.5",
                    "unitCode": "cbm"
                  }
                }
              ]
            }
          ],
          "totalGrossWeight": {
            "type": "QuantitativeValue",
            "value": "4038",
            "unitCode": "kg"
          },
          "totalGrossVolume": {
            "type": "QuantitativeValue",
            "value": "67.74",
            "unitCode": "cbm"
          },
          "totalNumberOfPackages": 622,
          "totalItemQuantity": 820
        },
        "proof": {
          "type": "Ed25519Signature2018",
          "created": "2022-06-14T11:24:28Z",
          "verificationMethod": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U#z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
          "proofPurpose": "assertionMethod",
          "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..FTNdmNsC0E1j2tq2sXZPB0k7vFcdmT0aSBFWbvIm_tH_XVasvk5haAeLanZK4gKIYFlJ9qFEtgGYPlrVbe8lBA"
        }
      }
       [
        {
          keyword: 'const',
          dataPath: '/@context/0',
          schemaPath: '#/properties/%40context/items/const',
          params: { allowedValue: [Array] },
          message: 'should be equal to constant'
        }
      ]

      51 |         const isValid = ajv.validate(s.$id, input);
      52 |         if (!isValid) {
    > 53 |           console.error(s.$linkedData.term, '\n', s.example, '\n', ajv.errors);
         |                   ^
      54 |         }
      55 |
      56 |         return true;

      at __tests__/schemas-sanity.test.js:53:19
          at async Promise.all (index 138)
      at Object.<anonymous> (__tests__/schemas-sanity.test.js:37:18)

    console.error
      ProformaInvoiceCertificate
       {
        "@context": [
          "https://www.w3.org/2018/credentials/v1",
          "https://w3id.org/traceability/v1"
        ],
        "id": "did:key:z6MkhNsCYEQQWJdyAbfaMZHz4UG6UZoQUGot7z7tBNsbz1JG",
        "type": [
          "VerifiableCredential",
          "CommercialInvoiceCertificate"
        ],
        "name": "Commercial Invoice Certificate",
        "issuanceDate": "2022-02-23T11:55:00Z",
        "issuer": {
          "id": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
          "type": "Entity",
          "name": "Aishi Metal Shinzo Co., Ltd.",
          "address": {
            "type": [
              "PostalAddress"
            ],
            "organizationName": "Aishi Metal Shinzo Co., Ltd.",
            "streetAddress": "1651, Shimonakano, Yoshida",
            "addressLocality": "Tsubame-shi",
            "addressRegion": "Niigata-ken",
            "postalCode": "959-0215",
            "addressCountry": "Japan"
          },
          "entityType": "Organization"
        },
        "credentialSubject": {
          "type": [
            "Invoice"
          ],
          "portOfEntry": {
            "type": "Place",
            "unLocode": "USLGB"
          },
          "destinationCountry": "MEX",
          "purchaseDate": "2021-02-21",
          "seller": {
            "type": [
              "Organization"
            ],
            "address": {
              "type": [
                "PostalAddress"
              ],
              "organizationName": "Aishi Metal Shinzo Co., Ltd.",
              "streetAddress": "1651, Shimonakano, Yoshida",
              "addressLocality": "Tsubame-shi",
              "addressRegion": "Niigata-ken",
              "postalCode": "959-0215",
              "addressCountry": "Japan"
            }
          },
          "buyer": {
            "type": [
              "Organization"
            ],
            "address": {
              "type": [
                "PostalAddress"
              ],
              "organizationName": "Generic Motors of America",
              "streetAddress": "12 Generic Motors Dr",
              "addressLocality": "Detroit",
              "addressRegion": "Michigain",
              "postalCode": "48232-5170",
              "addressCountry": "USA"
            }
          },
          "shipToParty": {
            "type": [
              "Organization"
            ],
            "address": {
              "type": [
                "PostalAddress"
              ],
              "organizationName": "Generic Motors of America",
              "streetAddress": "12 Generic Motors Dr",
              "addressLocality": "Detroit",
              "addressRegion": "Michigain",
              "postalCode": "48232-5170",
              "addressCountry": "USA"
            }
          },
          "itemsShipped": [
            {
              "type": "TradeLineItem",
              "product": {
                "manufacturer": {
                  "type": "Organization",
                  "address": {
                    "type": "PostalAddress",
                    "organizationName": "Aishi Metal Shinzo Co., Ltd.",
                    "streetAddress": "1651, Shimonakano, Yoshida",
                    "addressLocality": "Tsubame-shi",
                    "addressRegion": "Niigata-ken",
                    "postalCode": "959-0215",
                    "addressCountry": "Japan"
                  }
                },
                "description": "UNS S30400 chromium-nickel stainless steel rolls.",
                "weight": {
                  "type": "QuantitativeValue",
                  "unitCode": "lbs",
                  "value": "16500"
                }
              },
              "itemCount": 5,
              "tradeLineItemWeight": {
                "type": "QuantitativeValue",
                "value": "82500",
                "unitCode": "lbs"
              },
              "priceSpecification": {
                "type": "PriceSpecification",
                "price": 5200,
                "priceCurrency": "USD"
              }
            },
            {
              "type": "TradeLineItem",
              "product": {
                "manufacturer": {
                  "type": "Organization",
                  "address": {
                    "type": "PostalAddress",
                    "organizationName": "Aishi Metal Shinzo Co., Ltd.",
                    "streetAddress": "1651, Shimonakano, Yoshida",
                    "addressLocality": "Tsubame-shi",
                    "addressRegion": "Niigata-ken",
                    "postalCode": "959-0215",
                    "addressCountry": "Japan"
                  }
                },
                "description": "Galvalannealed ASTM A-653 zinc-iron alloy-coated steel sheets.",
                "weight": {
                  "type": "QuantitativeValue",
                  "value": "12680",
                  "unitCode": "lbs"
                }
              },
              "itemCount": 20,
              "tradeLineItemWeight": {
                "type": "QuantitativeValue",
                "value": "253600",
                "unitCode": "lbs"
              },
              "priceSpecification": {
                "type": "PriceSpecification",
                "price": 4400,
                "priceCurrency": "USD"
              }
            }
          ],
          "totalWeight": {
            "type": "QuantitativeValue",
            "value": "336100",
            "unitCode": "lbs"
          },
          "totalPaymentDue": {
            "type": "PriceSpecification",
            "price": 9600,
            "priceCurrency": "USD"
          }
        },
        "proof": {
          "type": "Ed25519Signature2018",
          "created": "2022-06-20T15:28:52Z",
          "verificationMethod": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U#z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
          "proofPurpose": "assertionMethod",
          "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..IKOohkBcgBK8sWr7noEWFguCGuSL_tu2Bo_-6Mp7_f8KSA9XdS2XrVSO2u9kN4sL2xaNjEaK1-niwf6VIeHpBw"
        }
      }
       [
        {
          keyword: 'const',
          dataPath: '/@context/0',
          schemaPath: '#/properties/%40context/items/const',
          params: { allowedValue: [Array] },
          message: 'should be equal to constant'
        }
      ]

      51 |         const isValid = ajv.validate(s.$id, input);
      52 |         if (!isValid) {
    > 53 |           console.error(s.$linkedData.term, '\n', s.example, '\n', ajv.errors);
         |                   ^
      54 |         }
      55 |
      56 |         return true;

      at __tests__/schemas-sanity.test.js:53:19
          at async Promise.all (index 139)
      at Object.<anonymous> (__tests__/schemas-sanity.test.js:37:18)

    console.error
      PurchaseOrderCertificate
       {
        "@context": [
          "https://www.w3.org/2018/credentials/v1",
          "https://w3id.org/traceability/v1"
        ],
        "id": "https://example.com/credential/123",
        "type": [
          "VerifiableCredential",
          "PurchaseOrderCertificate"
        ],
        "name": "Purchase Order Certificate",
        "description": "This document includes recommended purchase order fields.",
        "relatedLink": [],
        "issuanceDate": "2019-12-11T03:50:55Z",
        "issuer": {
          "id": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
          "type": "Organization",
          "name": "Waters Inc",
          "description": "Stand-alone executive benchmark",
          "address": {
            "type": "PostalAddress",
            "streetAddress": "027 Brakus Knoll",
            "addressLocality": "East Johnniemouth",
            "addressRegion": "Arizona",
            "postalCode": "25780-5840",
            "addressCountry": "Grenada"
          },
          "email": "Kendrick.Spinka57@example.org",
          "phoneNumber": "555-322-9464",
          "faxNumber": "555-766-1744"
        },
        "credentialSubject": {
          "type": [
            "PurchaseOrder"
          ],
          "portOfEntry": {
            "type": "Place",
            "unLocode": "USLGB"
          },
          "purchaseOrderNo": "fe71665a-e7b3-49ba-ac89-82fc2bf1e877",
          "destinationCountry": "MEX",
          "orderDate": "2021-02-21",
          "seller": {
            "type": [
              "Organization"
            ],
            "address": {
              "type": [
                "PostalAddress"
              ],
              "organizationName": "Aishi Metal Shinzo Co., Ltd.",
              "streetAddress": "1651, Shimonakano, Yoshida",
              "addressLocality": "Tsubame-shi",
              "addressRegion": "Niigata-ken",
              "postalCode": "959-0215",
              "addressCountry": "Japan"
            }
          },
          "buyer": {
            "type": [
              "Organization"
            ],
            "address": {
              "type": [
                "PostalAddress"
              ],
              "organizationName": "Generic Motors of America",
              "streetAddress": "12 Generic Motors Dr",
              "addressLocality": "Detroit",
              "addressRegion": "Michigain",
              "postalCode": "48232-5170",
              "addressCountry": "USA"
            }
          },
          "itemsShipped": [
            {
              "type": "TradeLineItem",
              "product": {
                "manufacturer": {
                  "type": "Organization",
                  "address": {
                    "type": "PostalAddress",
                    "organizationName": "Aishi Metal Shinzo Co., Ltd.",
                    "streetAddress": "1651, Shimonakano, Yoshida",
                    "addressLocality": "Tsubame-shi",
                    "addressRegion": "Niigata-ken",
                    "postalCode": "959-0215",
                    "addressCountry": "Japan"
                  }
                },
                "description": "UNS S30400 chromium-nickel stainless steel rolls.",
                "weight": {
                  "type": "QuantitativeValue",
                  "unitCode": "lbs",
                  "value": "16500"
                }
              },
              "itemCount": 5,
              "tradeLineItemWeight": {
                "type": "QuantitativeValue",
                "value": "82500",
                "unitCode": "lbs"
              },
              "priceSpecification": {
                "type": "PriceSpecification",
                "price": 5200,
                "priceCurrency": "USD"
              }
            },
            {
              "type": "TradeLineItem",
              "product": {
                "manufacturer": {
                  "type": "Organization",
                  "address": {
                    "type": "PostalAddress",
                    "organizationName": "Aishi Metal Shinzo Co., Ltd.",
                    "streetAddress": "1651, Shimonakano, Yoshida",
                    "addressLocality": "Tsubame-shi",
                    "addressRegion": "Niigata-ken",
                    "postalCode": "959-0215",
                    "addressCountry": "Japan"
                  }
                },
                "description": "Galvalannealed ASTM A-653 zinc-iron alloy-coated steel sheets.",
                "weight": {
                  "type": "QuantitativeValue",
                  "value": "12680",
                  "unitCode": "lbs"
                }
              },
              "itemCount": 20,
              "tradeLineItemWeight": {
                "type": "QuantitativeValue",
                "value": "253600",
                "unitCode": "lbs"
              },
              "priceSpecification": {
                "type": "PriceSpecification",
                "price": 4400,
                "priceCurrency": "USD"
              }
            }
          ],
          "totalWeight": {
            "type": "QuantitativeValue",
            "value": "336100",
            "unitCode": "lbs"
          },
          "totalOrderAmount": {
            "type": "PriceSpecification",
            "price": 9600,
            "priceCurrency": "USD"
          }
        },
        "proof": {
          "type": "Ed25519Signature2018",
          "created": "2022-06-20T15:28:52Z",
          "verificationMethod": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U#z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
          "proofPurpose": "assertionMethod",
          "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..X93MCiJwjgzzmWZTE9ay-Zc5i_gcXAWrrbK2O96N5OeD-SAZbXeCcsoyRe17MtUz0QaVYR4VMx75lHG4u-23Bg"
        }
      }
       [
        {
          keyword: 'const',
          dataPath: '/@context/0',
          schemaPath: '#/properties/%40context/items/const',
          params: { allowedValue: [Array] },
          message: 'should be equal to constant'
        }
      ]

      51 |         const isValid = ajv.validate(s.$id, input);
      52 |         if (!isValid) {
    > 53 |           console.error(s.$linkedData.term, '\n', s.example, '\n', ajv.errors);
         |                   ^
      54 |         }
      55 |
      56 |         return true;

      at __tests__/schemas-sanity.test.js:53:19
          at async Promise.all (index 140)
      at Object.<anonymous> (__tests__/schemas-sanity.test.js:37:18)

    console.error
      SIMASteelImportLicenseApplicationCertificate
       {
        "@context": [
          "https://www.w3.org/2018/credentials/v1",
          "https://w3id.org/traceability/v1"
        ],
        "id": "did:key:z6MknrcKsbzfy6kKFxtJQHxq43zHofhBuUqB6QGvvqF6FX7c",
        "type": [
          "VerifiableCredential",
          "SIMASteelImportLicenseApplicationCertificate"
        ],
        "issuer": {
          "type": "Organization",
          "id": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
          "name": "Maxi Acero Mexicano",
          "description": "Fusión y fabricación de acero sólido",
          "address": {
            "type": "PostalAddress",
            "streetAddress": "Avenida Carlos 100",
            "addressLocality": "Hernádez de Mara",
            "addressRegion": "Nuevo Leon",
            "postalCode": "32200",
            "addressCountry": "Mexico"
          },
          "email": "info@example.net",
          "phoneNumber": "555-127-7813"
        },
        "issuanceDate": "2022-02-28T11:23:00Z",
        "credentialSubject": {
          "type": "SIMASteelImportLicense",
          "applicantCompany": {
            "type": "Organization",
            "name": "Maxi Acero Mexicano",
            "description": "Fusión y fabricación de acero sólido",
            "address": {
              "type": "PostalAddress",
              "streetAddress": "Avenida Carlos 100",
              "addressLocality": "Hernádez de Mara",
              "addressRegion": "Nuevo Leon",
              "postalCode": "32200",
              "addressCountry": "Mexico"
            },
            "email": "info@example.net",
            "phoneNumber": "555-127-7813"
          },
          "customsEntryNumber": 34001239,
          "importer": {
            "type": "Organization",
            "name": "American Prime Steel Inc.",
            "description": "Quality Steel since 1952",
            "address": {
              "type": "PostalAddress",
              "streetAddress": "1551 Keebler Knoll",
              "addressLocality": "Vivianeburgh",
              "addressRegion": "Oregon",
              "postalCode": "47090",
              "addressCountry": "US"
            },
            "email": "contact@example.net",
            "phoneNumber": "555-716-2400"
          },
          "exporter": {
            "type": "Organization",
            "name": "Maxi Acero Mexicano",
            "description": "Fusión y fabricación de acero sólido",
            "address": {
              "type": "PostalAddress",
              "streetAddress": "Avenida Carlos 100",
              "addressLocality": "Hernádez de Mara",
              "addressRegion": "Nuevo Leon",
              "postalCode": "32200",
              "addressCountry": "Mexico"
            },
            "email": "info@example.net",
            "phoneNumber": "555-127-7813"
          },
          "manufacturer": {
            "type": "Organization",
            "name": "Maxi Acero Mexicano",
            "description": "Fusión y fabricación de acero sólido",
            "address": {
              "type": "PostalAddress",
              "streetAddress": "Avenida Carlos 100",
              "addressLocality": "Hernádez de Mara",
              "addressRegion": "Nuevo Leon",
              "postalCode": "32200",
              "addressCountry": "Mexico"
            },
            "email": "info@example.net",
            "phoneNumber": "555-127-7813"
          },
          "countryOfOrigin": "MX",
          "countryOfExportation": "MX",
          "countryOfMeltAndPour": "MX",
          "expectedPortOfEntry": "USMOB",
          "expectedDateOfExport": "2022-04-02T08:00:00Z",
          "expectedDateOfImport": "2022-04-09T10:30:00Z",
          "productInformation": [
            {
              "type": [
                "SIMASteelImportProductSpecifier"
              ],
              "steelProduct": {
                "type": "SteelProduct",
                "heatNumber": "841",
                "specification": "ASTM-66272",
                "grade": "95913",
                "originalCountryOfMeltAndPour": "MX",
                "weight": 3200,
                "weightUnit": "https://service.unece.org/trade/uncefact/vocabulary/rec20/#kilogram",
                "commodity": {
                  "type": "Commodity",
                  "commodityCode": "721320",
                  "commodityCodeType": "HS",
                  "description": "Steel Coils"

```

**Comment by TallTed** [comment]
Might be better to put the warnings in a gist or similar external location, linked to from here, rather than putting such a giant text block (which might then repeat partially or completely after PR(s) get(s) applied)...

**Comment by OR13** [comment]
We should surface warnings in the spec text.... like we do for undefined terms.

**Comment by BenjaminMoe** [comment]
The errors getting thrown here are schema errors that surface when proofs are broken. I think the solution here would be to enable json schema errors in the CI.

**Comment by BenjaminMoe** [comment]
PR: Enable JSON Schema Check in CI

**Comment by BenjaminMoe** [comment]
Surface Errors in Respec document.

**Comment by nissimsan** [comment]
We did this.
